openapi: 3.0.0
info:
  title: API to interact with the minesweeper server
  description: This API allows a client to interact with the server to play the minesweeper game
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /games:
    post:
      description: Creates a new minesweeper game
      parameters:
        - in: query
          name: horizontal_size
          schema:
            type: integer
          description: The size of the game board in the horizontal dimension. Must be a non-zero positive integer.
          required: true
        - in: query
          name: vertical_size
          schema:
            type: integer
          description: The size of the game board in the vertical dimension. Must be a non-zero positive integer.
          required: true
      responses:
        "201":
          description: The game has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
        "400":
          description: The board could not be created due to invalid input parameters.
          content:
            application/json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
components:
  schemas:
    game:
      title: A game resource containing the game state as visible to the user
      type: object
      properties:
        board:
          $ref: '#/components/schemas/board'
        id:
          type: string
          format: uuid
          description: The unique identifier of the game
      required:
        - board

    board:
      type: object
      description: A two-dimensional array of cells that describe the game board state
      properties:
        horizontal_size:
          type: integer
          description: The size of the game board in the horizontal dimension.
        vertical_size:
          type: integer
          description: The size of the game board in the vertical dimension.
        cells:
          type: array
          items:
            type: array
            items:
              items:
                $ref: '#/components/schemas/cell'
        number_of_mines:
          type: integer
      required:
        - horizontal_size
        - vertical_size
        - cells
        - number_of_mines

    cell:
      type: object
      properties:
        horizontal_index:
          type: integer
        vertical_index:
          type: integer
        number_of_adjacent_mines:
          type: integer
          description: Indicates the number of mines which are adjacent to this cell. Must be between 0 and 8.
      required:
        - horizontal_index
        - vertical_index